#!/usr/bin/env bash
# Fake multi-node on one host: Frontend project + Workers project via LAN IP.
#
# Prerequisites: IMAGE_TAG / model paths in .env (see .env.frontend.example).
# Optional: .env.workers-sim.example / MULTINODE_SIM_IP.
#
# Usage (from docker-compose/):
#   ./simulate_multinode_localhost.sh
#   ./validate_multinode_localhost.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

if [[ -f "${SCRIPT_DIR}/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  . "${SCRIPT_DIR}/.env"
  set +a
fi
if [[ -f "${SCRIPT_DIR}/.env.workers-sim" ]]; then
  set -a
  # shellcheck disable=SC1091
  . "${SCRIPT_DIR}/.env.workers-sim"
  set +a
elif [[ -f "${SCRIPT_DIR}/.env.workers-sim.example" ]]; then
  set -a
  # shellcheck disable=SC1091
  . "${SCRIPT_DIR}/.env.workers-sim.example"
  set +a
fi

FRONTEND_PROJECT="${FRONTEND_PROJECT:-io-frontend}"
WORKERS_PROJECT="${WORKERS_PROJECT:-io-workers}"
ROUTER_PORT="${ROUTER_PORT:-8800}"
REGISTRY_PORT="${REGISTRY_PORT:-18000}"
EMBEDDING_PORT="${EMBEDDING_PORT:-20003}"
WORKER_9G_API_PORT="${WORKER_9G_API_PORT:-8102}"
WORKER_QWEN_API_PORT="${WORKER_QWEN_API_PORT:-8200}"
CAPTURE_TIMEOUT_SEC="${CAPTURE_TIMEOUT_SEC:-7200}"
CAPTURE_POLL_SEC="${CAPTURE_POLL_SEC:-30}"

FRONTEND_CONTAINER="${FRONTEND_CONTAINER:-infiniorch-frontend-opt-20260811}"
WORKER_9G_CONTAINER="${WORKER_9G_CONTAINER:-infiniorch-worker-9g-8100-20260811}"
WORKER_QWEN_CONTAINER="${WORKER_QWEN_CONTAINER:-infiniorch-worker-qwen-paged-8200-20260811}"
WORKER_EMB_CONTAINER="${WORKER_EMB_CONTAINER:-infiniorch-worker-embeddings-20002-20260811}"

log_step() {
  echo ""
  echo "=========================================="
  echo "$1"
  echo "=========================================="
}

resolve_sim_ip() {
  if [[ -n "${MULTINODE_SIM_IP:-}" ]]; then
    echo "${MULTINODE_SIM_IP}"
    return 0
  fi
  local ip
  ip="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  if [[ -z "${ip}" ]]; then
    echo "Error: could not detect LAN IP; set MULTINODE_SIM_IP" >&2
    return 1
  fi
  echo "${ip}"
}

SIM_IP="$(resolve_sim_ip)"
if [[ "${SIM_IP}" == "127.0.0.1" || "${SIM_IP}" == "::1" ]]; then
  echo "Error: MULTINODE_SIM_IP must be a LAN address, not ${SIM_IP}" >&2
  exit 1
fi

log_step "[0] Fake multi-node IP=${SIM_IP}"

# Container → host-LAN-IP → published port requires forwarding (same as old slave-sim).
if [[ "$(sysctl -n net.ipv4.ip_forward 2>/dev/null || echo 0)" != "1" ]]; then
  echo "  Enabling net.ipv4.ip_forward=1 (required for Frontend↔worker LAN hairpin)"
  sysctl -w net.ipv4.ip_forward=1 >/dev/null
fi
sysctl -w net.bridge.bridge-nf-call-iptables=1 >/dev/null 2>&1 || true

log_step "[1] Tear down conflicting stacks (default + sim projects)"
COMPOSE_PROJECT_NAME=docker-compose ./compose.sh --profile frontend --profile workers down 2>/dev/null || true
COMPOSE_PROJECT_NAME="${FRONTEND_PROJECT}" ./compose.sh --profile frontend down 2>/dev/null || true
COMPOSE_PROJECT_NAME="${WORKERS_PROJECT}" ./compose.sh --profile workers down 2>/dev/null || true
# Historical container names from pre-rename stack
for c in \
  infiniorch-master-opt-20260811 \
  infiniorch-worker-master-9g-8100-20260811 \
  infiniorch-worker-master-qwen-paged-8200-20260811 \
  infiniorch-worker-master-embeddings-20002-20260811 \
  "${FRONTEND_CONTAINER}" \
  infiniorch-etcd-opt-20260811 \
  "${WORKER_9G_CONTAINER}" \
  "${WORKER_QWEN_CONTAINER}" \
  "${WORKER_EMB_CONTAINER}"; do
  docker rm -f "${c}" 2>/dev/null || true
done

log_step "[2] Write .env.workers for LAN discovery"
cat > "${SCRIPT_DIR}/.env.workers" <<EOF
# Generated by simulate_multinode_localhost.sh — do not commit secrets.
IMAGE_TAG=${IMAGE_TAG}
ETCD_IMAGE_TAG=${ETCD_IMAGE_TAG:-quay.io/coreos/etcd:v3.7.0}
EMBEDDING_IMAGE_TAG=${EMBEDDING_IMAGE_TAG:-${IMAGE_TAG}}
FRONTEND_HOST=${SIM_IP}
ADVERTISE_HOST=${SIM_IP}
REGISTRY_PORT=${REGISTRY_PORT}
ROUTER_PORT=${ROUTER_PORT}
FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT:-${ROUTER_PORT}}
EMBEDDING_PORT=20002
ROUTER_URL=http://${SIM_IP}:${ROUTER_PORT}
REGISTRY_URL=http://${SIM_IP}:${REGISTRY_PORT}
ETCD_ENDPOINTS=http://${SIM_IP}:2379
# Host publish ports must equal container listen ports when ADVERTISE_HOST is a LAN IP
# (registry advertises container port; same-host remaps like 8102 break multi-node health).
WORKER_9G_API_PORT=8100
WORKER_9G_BABYSITTER_PORT=8101
WORKER_QWEN_API_PORT=8200
WORKER_QWEN_BABYSITTER_PORT=8201
MODEL1_DIR=${MODEL1_DIR}
QWEN3_32B_DIR=${QWEN3_32B_DIR}
EMBEDDING_MODEL_DIR=${EMBEDDING_MODEL_DIR}
PIECEWISE_INDUCTOR_CACHE_DIR=${PIECEWISE_INDUCTOR_CACHE_DIR:-../cache/piecewise_inductor}
IO_RUST_RELEASE_DIR=${IO_RUST_RELEASE_DIR:-}
COMPOSE_SUBNET=172.29.0.0/16
CACHE_TYPE_ROUTING_THRESHOLD=${CACHE_TYPE_ROUTING_THRESHOLD:-51200}
EOF

log_step "[3] Start Frontend project (${FRONTEND_PROJECT})"
COMPOSE_PROJECT_NAME="${FRONTEND_PROJECT}" \
  COMPOSE_SUBNET="${FRONTEND_COMPOSE_SUBNET:-172.28.0.0/16}" \
  ./compose.sh --profile frontend up -d --force-recreate

echo -n "  Waiting for Frontend /health..."
deadline=$((SECONDS + 120))
until curl -sf --noproxy "*" "http://${SIM_IP}:${ROUTER_PORT}/health" >/dev/null 2>&1; do
  if [[ "${SECONDS}" -ge "${deadline}" ]]; then
    echo " TIMEOUT"
    exit 1
  fi
  echo -n "."
  sleep 2
done
echo " OK"

log_step "[4] Start Workers project (${WORKERS_PROJECT})"
COMPOSE_PROJECT_NAME="${WORKERS_PROJECT}" \
  COMPOSE_ENV_FILE="${SCRIPT_DIR}/.env.workers" \
  COMPOSE_SUBNET="${WORKERS_COMPOSE_SUBNET:-172.29.0.0/16}" \
  ./compose.sh --profile workers up -d --force-recreate

wait_worker() {
  local c="$1"
  local label="$2"
  local deadline=$((SECONDS + CAPTURE_TIMEOUT_SEC))
  echo "  Waiting for ${label} (${c})..."
  while [[ "${SECONDS}" -lt "${deadline}" ]]; do
    if ! docker ps --format '{{.Names}}' | grep -qx "${c}"; then
      echo "    not running yet..."
      sleep "${CAPTURE_POLL_SEC}"
      continue
    fi
    # embeddings: babysitter only; LLM workers: look for engine ready hints
    if [[ "${c}" == "${WORKER_EMB_CONTAINER}" ]]; then
      if curl -sf --noproxy "*" "http://${SIM_IP}:${EMBEDDING_PORT}/v1/embeddings" \
        -H "Content-Type: application/json" \
        -d '{"model":"text-embedding-ada-002","input":"hi"}' 2>/dev/null | grep -q '"object"'; then
        echo "    READY ${label}"
        return 0
      fi
    else
      local logs
      logs="$(docker exec "${c}" bash -lc 'f=$(ls -t /app/logs/babysitter_*.log 2>/dev/null | head -1); tail -300 "$f" 2>/dev/null' 2>/dev/null || true)"
      if echo "${logs}" | grep -Eqi 'LLMEngine initialized|Uvicorn running|Application startup complete|C\+\+ capture complete|listening on'; then
        if curl -sf --connect-timeout 2 --noproxy "*" "http://${SIM_IP}:${ROUTER_PORT}/health" >/dev/null; then
          # Prefer models endpoint once registered
          if curl -sf --noproxy "*" "http://${SIM_IP}:${ROUTER_PORT}/v1/models" 2>/dev/null | grep -q '"id"'; then
            echo "    READY ${label} (models visible)"
            return 0
          fi
        fi
        echo "    engine logs look up for ${label}; waiting for registry..."
      fi
    fi
    sleep "${CAPTURE_POLL_SEC}"
  done
  echo "  WARN: timeout waiting for ${label}"
  return 1
}

log_step "[5] Wait for workers (SKIP_EMBEDDING=${SKIP_EMBEDDING:-0})"
if [[ "${SKIP_EMBEDDING:-0}" != "1" ]]; then
  wait_worker "${WORKER_EMB_CONTAINER}" "embeddings" || true
fi
# Ready when model appears on Frontend /v1/models (faster + reliable vs babysitter log scrape)
wait_model() {
  local model="$1"
  local label="$2"
  local deadline=$((SECONDS + CAPTURE_TIMEOUT_SEC))
  echo "  Waiting for model ${label} (${model}) on Frontend..."
  while [[ "${SECONDS}" -lt "${deadline}" ]]; do
    local models svcs
    models="$(curl -sf --noproxy "*" "http://${SIM_IP}:${ROUTER_PORT}/v1/models" 2>/dev/null || true)"
    svcs="$(curl -sf --noproxy "*" "http://${SIM_IP}:${REGISTRY_PORT}/services" 2>/dev/null || true)"
    if echo "${models}" | grep -q "\"id\":\"${model}\""; then
      echo "    READY ${label}"
      return 0
    fi
    # Require this model's own healthy registry entry on LAN IP (avoid matching sibling services).
    if echo "${svcs}" | python3 -c "
import json,sys
want_model='${model}'
sim='${SIM_IP}'
d=json.load(sys.stdin)
for s in d.get('services',[]):
  models=s.get('models') or []
  meta=(s.get('metadata') or {}).get('models') or []
  names=set(models)|set(meta)|{s.get('name','')}
  if want_model in names or any(want_model in str(x) for x in names):
    if s.get('host')==sim and s.get('healthy') is True:
      sys.exit(0)
sys.exit(1)
" 2>/dev/null; then
      echo "    READY ${label} (healthy on ${SIM_IP})"
      return 0
    fi
    sleep "${CAPTURE_POLL_SEC}"
  done
  echo "  WARN: timeout waiting for model ${label}"
  return 1
}
wait_model "9g_8b_thinking" "9g" || true
wait_model "Qwen3-32B" "qwen-paged" || true

echo ""
echo "Simulate done. Run: SKIP_EMBEDDING=${SKIP_EMBEDDING:-0} ./validate_multinode_localhost.sh"
echo "  MULTINODE_SIM_IP=${SIM_IP}"
echo "  FRONTEND_PROJECT=${FRONTEND_PROJECT} WORKERS_PROJECT=${WORKERS_PROJECT}"
echo ""
echo "Restore same-host stack later:"
echo "  COMPOSE_PROJECT_NAME=${WORKERS_PROJECT} ./compose.sh --profile workers down"
echo "  COMPOSE_PROJECT_NAME=${FRONTEND_PROJECT} ./compose.sh --profile frontend down"
echo "  COMPOSE_PROJECT_NAME=docker-compose ./compose.sh --profile frontend --profile workers up -d"
